### ISSUE TITLE
add const display console

### ISSUE THREAD

**Issue by robinja4** [hoggjt2/Studio2_refactoring#11]
change some const in the display method

**Comment by robinja4** [comment]
added HALF and QUARTER CONSOLE const

**Comment by hoggjt2** [comment]
This doesn't want to merge for some reason. I had a look but couldn't see an obvious issue. Any suggestions?

**Comment by SteveParker-github** [comment]
I've had a look and it is saying a conflict issue. I'm not sure if James wants to resolve the issue or i can attempt to fix it.

**Comment by robinja4** [comment]
resolved
